namespace _02_EmployeeDAOClass
{
    using System;

    using _01_DbContextForTheSoftUniDatabase;

    public class Test
    {
        public static void Main()
        {
            Employee employee = new Employee()
                {
                    FirstName = "Mincho",
                    MiddleName = "Georgiev",
                    LastName = "Dimitrov",
                    JobTitle = "Some job",
                    DepartmentID = 13,
                    ManagerID = 33,
                    HireDate = DateTime.Now.AddYears(-2),
                    Salary = 9999,
                    AddressID = 133
                };

            // 01. Insert an employee
            EmployeeDao.Add(employee);

            // 02. Print his/her primary key generated by the DB
            Console.WriteLine(employee.EmployeeID);

            // 03. Changes the employee first name and saves it to the database
            EmployeeDao.Modify(
                employee,
                "Georgi",
                "Petrov",
                "Mihajlov",
                "Driver",
                5,
                null,
                DateTime.Now.AddDays(-30),
                3333,
                null);

            Console.WriteLine(employee.FirstName + " " + employee.MiddleName + " " +
                employee.LastName + ", job: " + employee.JobTitle);

            // other tests:
            Employee emp = EmployeeDao.FindByKey(294);
            Console.WriteLine(emp.EmployeeID + " " + emp.FirstName + " " + emp.MiddleName + " " +
                emp.LastName + ", job: " + emp.JobTitle);

            EmployeeDao.Delete(emp);
            Employee deletedEmp = EmployeeDao.FindByKey(294);

            if (deletedEmp == null)
            {
                Console.WriteLine("Employee with ID 294, is deleted");
            }
        }
    }
}
